### ISSUE TITLE
Dragging outside of the bounds is glitchy

### ISSUE THREAD

**Issue by rwwagner90** [turban/Leaflet.Sync#21]
If you drag a map far outside of the bounds of the map, using noWrap = true, it will snap itself back to the bounds, but then everything gets all glitchy. I assume noWrap is just not supported, and if it were infinitely scrolling it would work better? Please advise.

**Comment by jieter** [comment]
@rwwagner90 can you clarify 'glitchy'?

http://turban.github.io/Leaflet.Sync/examples/nowrap.html

**Comment by rwwagner90** [comment]
@jieter That doesn't look like noWrap to me. If you zoom all the way out, the map clearly repeats itself. noWrap makes the map area only appear once.

**Comment by jieter** [comment]
Ah, I see, I have to set `noWrap: true` for both maps. updated: http://turban.github.io/Leaflet.Sync/examples/nowrap.html

That looks funky when zoomed out!

**Comment by jieter** [comment]
doh, have to set it on the TileLayer, not on the map...

**Comment by rwwagner90** [comment]
So you see the issue where it gets stuck and is glitchy right? If you drag the left map as far as you can to the left, the right map moves to wherever you dragged it to. It doesn't snap back, as noWrap should.

**Comment by jieter** [comment]
[AFAIK](http://leafletjs.com/reference.html#tilelayer-nowrap) no wrap is not about snapping back, only about which tiles to load.

**Comment by rwwagner90** [comment]
@jieter noWrap certainly does snap back. If it did not, you could scroll off into nothingness as far as you wanted

**Comment by jieter** [comment]
Yeah, and I think that will be the case if only noWrap is used on a TileLayer.

If I search for `noWrap` in http://cdn.leafletjs.com/leaflet-0.7.3/leaflet-src.js, I cannot find code that should move the view back to within the first and only world...

**Comment by rwwagner90** [comment]
@jieter Can you use the master version of Leaflet? I'm not sure what makes it snap back, but that should be the expected behavior, that noWrap enforces not being able to scroll into nothingness forever. Why would someone want to allow that?

**Comment by jieter** [comment]
`noWrap` is not in master: https://github.com/Leaflet/Leaflet/issues/2384

**Comment by rwwagner90** [comment]
You're correct, I forgot about that. I assume wrapLat and wrapLng will have the exact same issue though. The syncing just appears to take the values of where you drag, regardless of the wrap settings. It should take the values of where you drag, unless those values are further than the map bounds, and snap everything back.

**Comment by rio2311** [comment]
Bump!
Have almost same issue, when moving out of bounds, both maps just got stuck, with error

Uncaught RangeError: Maximum call stack size exceeded

**Comment by brandonxiang** [comment]
When I set Maxbounds for L.map, map does not work for a second while, with error

leaflet.js:6 Uncaught RangeError: Maximum call stack size exceeded

**Comment by jieter** [comment]
Minimal example to reproduce this:

```JavaScript
    var center = [59.336, 5.967];
    var zoom = 10;
    var bounds = L.latLngBounds([[50, 0], [60, 10]]);

    var map1 = L.map('map1', {maxBounds: bounds}).setView(center, zoom);
    var map2 = L.map('map2', {maxBounds: bounds});

    map1.sync(map2);
    map2.sync(map1);
```

**Comment by brandonxiang** [comment]
I figured it out. Sync.js is compatiable with leafletjs 1.0.0, and I used the version 0.7.7 before

**Comment by jieter** [comment]
Hmm, it indeed doesn't seem to be an issue with 1.1.0-beta.2.

**Comment by rwwagner90** [comment]
@jieter how is progress on this? I see you made some commits on a WIP

**Comment by jieter** [comment]
@rwwagner90 No real success yet, sorry.

**Comment by rwwagner90** [comment]
@jieter I'm inclined to close, as this no longer is something I care about, really. Please feel free to open again if you need it
