### ISSUE TITLE
How to manage same layer between 2 sync maps ?

### ISSUE THREAD

**Issue by sylvain-m** [turban/Leaflet.Sync#28]
Hello,

Perhaps it's more a question than an issue, but i don't know where to ask question about this Leaflet plugin.
I have to manage 2 sync map, in which some layers are the same.
If i use the same var for each one, i have conflicts on the layer control button.

To make it work, i have to state 2 var from the same parameters :
```
        var mylayer1 = L.tileLayer('mylayerurl', {mylayeroptions});
        var mylayer2 = L.tileLayer('mylayerurl', {mylayeroptions});
```

I do not think it's the best choice (layers URL and option are pretty big).

I have test with this, but it do not work :
```
        var mylayer = L.tileLayer('mylayerurl', {mylayeroptions});
        var mylayer1 = mylayer;
        var mylayer2 = mylayer;
```
Does someone could tell me the right method ?

Thanks in advance !

Sylvain M.

**Comment by jieter** [comment]
Use leaflet-clonelayer for this: https://github.com/jieter/leaflet-clonelayer

**Comment by sylvain-m** [comment]
Thanks : its perfect for me !
:+1:
