### ISSUE TITLE
Add cdn for Leaflet.Sync

### ISSUE THREAD

**Issue by PBrockmann** [turban/Leaflet.Sync#32]
I really appreciate this plugin and use it in an application I distribute (https://github.com/PBrockmann/wms-pyferret).
Would you be interested to make it available from https://cdnjs.com/ ("Request a lib" link) ?

Thanks

**Comment by jieter** [comment]
@PBrockmann what about using the [npm cdn](https://unpkg.com/#/), leaflet.sync can be found there: https://unpkg.com/leaflet.sync@0.0.5

**Comment by PBrockmann** [comment]
Ok perfect with unpkg.com that I discover.
Thanks

**Comment by PBrockmann** [comment]
I reopen this issue since I get ressources from cdnjs with http and not https.
When I tried https with my NW.js application, I get: 
:ERROR:cert_verify_proc_nss.cc(925)] CERT_PKIXVerifyCert for unpkg.com failed err=-8182

So could it be possible to add Leaflet.Sync on cdnjs ?
I will be then able to access it from a http request.

**Comment by PBrockmann** [comment]
Ok discover cdn.rawgit.com made for exactly to distribute ressources with http access.
http://cdn.rawgit.com/turban/Leaflet.Sync/master/L.Map.Sync.js or
http://cdn.rawgit.com/turban/Leaflet.Sync/0.0.5/L.Map.Sync.js
