### ISSUE TITLE
moveend event fired on synced map on every single drag (not at end)

### ISSUE THREAD

**Issue by Thuranel** [turban/Leaflet.Sync#34]
Hi,

I have been trying to call an event on a synced map when the user finishes moving the original map. Because there is no event called on the synced map by default and you have to programmatically fire the event, it is impossible in the current build to trigger a drag event on a synced map.

The only event that is fired when dragging is the 'moveend' event. Unfortunately, it is not working as expected. Here's is the function where the event is called:

```JavaScript
            originalMap.dragging._draggable._updatePosition = function () {
                L.Draggable.prototype._updatePosition.call(this);
                var self = this;
                originalMap._syncMaps.forEach(function (toSync) {
                    L.DomUtil.setPosition(toSync.dragging._draggable._element, self._newPos);
                    toSync.eachLayer(function (layer) {
                        if (layer._google !== undefined) {
                            layer._google.setCenter(originalMap.getCenter());
                        }
                    });
                    toSync.fire('moveend');
                });
            };
```

Since _updatePosition is called on every single drag movement, the moveend event is fired at every single tick. So what we actually have is a 'move' event. 

And here's a fiddle showing the issue: https://jsfiddle.net/Thuranel/zmp3qfqe/3/

So right now I'm trying to find a way to create a real 'moveend' event. So far all I've managed to do is hack my issue by triggering 'moveend' when these other events are triggered: 'load',  'dragend', 'zoomend'.

```JavaScript
            originalMap.on('zoomend', function () {
                originalMap._syncMaps.forEach(function (toSync) {
                    toSync.setView(originalMap.getCenter(), originalMap.getZoom(), NO_ANIMATION);
                  toSync.fire('moveend');
                });
            }, this);
          
            originalMap.on('dragend', function(){
              originalMap._syncMaps.forEach(function (toSync) {
                toSync.fire('moveend');
              });
            }, this);

            originalMap.on('load', function(){
              originalMap._syncMaps.forEach(function (toSync) {
                toSync.fire('moveend');
              });
            }, this);
```
Obviously this is not a perfect solution, so I've tried to create a custom event that is called when moveend is called.

```JavaScript
            originalMap.on('moveend', function(){
              originalMap._syncMaps.forEach(function (toSync) {
                toSync.fire('syncmoveend');
              });
            }, this);
```

But I would rather not create a new event if there is a way to trigger the event normally.

Any suggestions?

**Comment by Thuranel** [comment]
I still haven't found a way to trigger a real moveend event except when using a second event.

Anyway, what do you think of replacing ``toSync.fire('moveend');`` to ``toSync.fire('move');`` to better reflect the actual behavior?

So the drag function would look like this:

```
            originalMap.dragging._draggable._updatePosition = function () {
                L.Draggable.prototype._updatePosition.call(this);
                var self = this;
                originalMap._syncMaps.forEach(function (toSync) {
                    L.DomUtil.setPosition(toSync.dragging._draggable._element, self._newPos);
                    toSync.eachLayer(function (layer) {
                        if (layer._google !== undefined) {
                            layer._google.setCenter(originalMap.getCenter());
                        }
                    });
                    toSync.fire('move');
                });
            };
```

This would also allow me to make me to use a second event without additional events being triggered. (The second solution I posted in my first post doesn't really work right now because the 'moveend' event gets triggered all the time).

Anyway tell me what you think and I will make a pull request if you believe it's a good idea to replace 'moveend' to 'move' to better reflect the actual behavior.

**Comment by jieter** [comment]
Thanks for diving in!

To me, when firing `move` events, intuitively it should be followed by a `moveend` event. I have no problems with firing `move` instead of `moveend`, please open a PR. It's helpful to have tests describing the expected behavior and giving a clear reasoning in the PR description.
